spring:
  redis:
    host: 192.168.43.151
    port: 7001
    database: 16
    password: 888888
#    password:
    encode: utf-8
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
#    timeout: 15000  #lettuce默认的超时时间为60s,源码见LettuceClientConfigurationBuilder
